### PR TITLE
Add option to perform haptic feedback when swipe threshold is crossed

### PR DESCRIPTION
**Pull request by alashow**

### CODE REVIEW

**Comment by alashow** [comment]
We could also add haptic feedback when visible action changes:
```kotlin
if (enableHapticFeedbackWhenActionChanges) {
        LaunchedEffect(visibleAction) {
            if (thresholdCrossed && visibleAction != null) {
                hapticFeedback.performHapticFeedback(HapticFeedbackType.TextHandleMove)
            }
        }
    }
```

Not sure if this will improve UX, feels wrong and right at the same time..

Edit: above implementation is buggy, not sure why yet

**Comment by alashow** [comment]
Also, I've noticed some apps like Gmail, Telegram perform haptic feedback when threshold is crossed back (indicating action won't be executed). Maybe we should create callbacks for these events (threshold crossed & visible action change) so it can be implemented in app side.

**Comment by saket** [comment]
I agree it'll be best to expose these callbacks and let apps play the haptic feedback themselves. Let me try it out.

**Comment by saket** [comment]
I ended up changing my mind that `swipe` should play haptic feedback by default. Thanks for the idea!

> above implementation is buggy, not sure why yet

Do you remember what exactly was buggy about this? My implementation looks very similar to yours but it seems to be working well:

https://github.com/saket/swipe/blob/a071a6ca018346ed38e7fe5bd98b2e083eb8e8d4/library/src/commonMain/kotlin/me/saket/swipe/SwipeableActionsBox.kt#L105-L110

**Comment by alashow** [comment]
I forgot what was the bug.. but it wasn't hard to reproduce so your implementation is probably fine.

**Pull request closed without merging**
